allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@next/env@16.3.7'
  - '@next/eslint-plugin-next@16.3.7'
  - '@next/swc-darwin-arm64@16.3.7'
  - '@next/swc-darwin-x64@16.3.7'
  - '@next/swc-linux-arm64-gnu@16.3.7'
  - '@next/swc-linux-arm64-musl@16.3.7'
  - '@next/swc-linux-x64-gnu@16.3.7'
  - '@next/swc-linux-x64-musl@16.3.7'
  - '@next/swc-win32-arm64-msvc@16.3.7'
  - '@next/swc-win32-x64-msvc@16.3.7'
  - '@opennextjs/cloudflare@1.20.7'
  - eslint-config-next@16.3.7
  - next@16.3.7
  - wrangler@4.143.0
